package io.swzxsyh.manager.api.dto;

import io.swzxsyh.payment.domain.OrderStatus;
import io.swzxsyh.payment.domain.PaymentMethod;
import io.swzxsyh.payment.domain.PaymentOrder;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/** 管理端订单视图，面向运营排障和对账，允许展示完整路由、费用、回调与内部处理字段。 */
public record ManagerPaymentOrderView(
    String cryptoOrderNo,
    String merchantId,
    String merchantOrderNo,
    BigDecimal amount,
    String currency,
    String chain,
    String token,
    String tokenAddress,
    String walletAddress,
    String walletAccountType,
    PaymentMethod paymentMethod,
    String tokenRouteType,
    String routeReason,
    OrderStatus status,
    String paymentAddress,
    String contractAddress,
    String contractCallData,
    String gasPayerMode,
    String gasReason,
    BigDecimal gasEstimatedFeeWei,
    boolean gasCustomerBalanceSufficient,
    boolean gasPlatformBalanceSufficient,
    String gasFallbackSuggestion,
    String derivedAddressPoolKey,
    String derivedAddressLeaseId,
    BigDecimal transactionFeeRate,
    BigDecimal minimumFee,
    BigDecimal fixedFee,
    BigDecimal gatewayFee,
    BigDecimal taxRate,
    String feeSettlementMode,
    BigDecimal transactionFee,
    BigDecimal taxFee,
    BigDecimal totalFee,
    BigDecimal settlementAmount,
    String paymentTxHash,
    BigDecimal realAmount,
    LocalDateTime paidAt,
    boolean latePayment,
    LocalDateTime latePaymentAt,
    String notifyUrl,
    String returnUrl,
    LocalDateTime expireTime,
    LocalDateTime createdAt,
    LocalDateTime updatedAt
) {

  public static ManagerPaymentOrderView from(PaymentOrder order) {
    return new ManagerPaymentOrderView(
        order.getCryptoOrderNo(),
        order.getMerchantId(),
        order.getMerchantOrderNo(),
        order.getAmount(),
        order.getCurrency(),
        order.getChain(),
        order.getToken(),
        order.getTokenAddress(),
        order.getWalletAddress(),
        order.getWalletAccountType(),
        order.getPaymentMethod(),
        order.getTokenRouteType(),
        order.getRouteReason(),
        order.getStatus(),
        order.getPaymentAddress(),
        order.getContractAddress(),
        order.getContractCallData(),
        order.getGasPayerMode(),
        order.getGasReason(),
        order.getGasEstimatedFeeWei(),
        order.isGasCustomerBalanceSufficient(),
        order.isGasPlatformBalanceSufficient(),
        order.getGasFallbackSuggestion(),
        order.getDerivedAddressPoolKey(),
        order.getDerivedAddressLeaseId(),
        order.getTransactionFeeRate(),
        order.getMinimumFee(),
        order.getFixedFee(),
        order.getGatewayFee(),
        order.getTaxRate(),
        order.getFeeSettlementMode(),
        order.getTransactionFee(),
        order.getTaxFee(),
        order.getTotalFee(),
        order.getSettlementAmount(),
        order.getPaymentTxHash(),
        order.getRealAmount(),
        order.getPaidAt(),
        order.isLatePayment(),
        order.getLatePaymentAt(),
        order.getNotifyUrl(),
        order.getReturnUrl(),
        order.getExpireTime(),
        order.getCreatedAt(),
        order.getUpdatedAt());
  }
}
