package io.swzxsyh.payment.signature;

public enum SignatureScope {
  ORDER_CREATE,
  ORDER_QUERY,
  ORDER_METHOD_SELECT,
  SUBSCRIPTION_CREATE,
  SUBSCRIPTION_QUERY,
  SUBSCRIPTION_SETUP,
  SUBSCRIPTION_MANAGE,
  GATEWAY_CREATE,
  CALLBACK_SIGN
}
